name: Publish release package to Maven Central and GH Packages
on:
  workflow_dispatch:
    inputs:
      publish_gh:
        description: 'Publish to GH Packages'
        required: true
        default: 'true'
      publish_oss:
        description: 'Publish to Sonatype'
        required: true
        default: 'true'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Chmod
        run: chmod +x gradlew

      - name: Remove -SNAPSHOT suffix
        run: ./gradlew removeSnapshotSuffix

      - name: Build and Test
        run: ./gradlew clean build

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSS_GPG_KEY }}
          passphrase: ${{ secrets.OSS_GPG_KEY_PASS }}

      - name: Test and publish package
        if: ${{ github.event.inputs.publish_gh == 'true' || github.event.inputs.publish_oss == 'true' }}
        run: ./gradlew -PenableSigning=true -PpublishGH=${{ github.event.inputs.publish_gh }} -PpublishOSS=${{ github.event.inputs.publish_oss }} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSS_USER: ${{ secrets.OSS_USER }}
          OSS_PASS: ${{ secrets.OSS_PASS }}

      - name: Get the current version
        id: get_version
        run: echo "RELEASE_VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          message: 'Publish release'

#      - name: Create GitHub Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ env.RELEASE_VERSION }}
#          release_name: ${{ env.RELEASE_VERSION }}
#          body: |
#            Release of version ${{ env.RELEASE_VERSION }}.
#          draft: true
#          prerelease: false


      - name: Create GitHub Release
        uses: actions/gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: |
            Release of version ${{ env.RELEASE_VERSION }}.
          draft: true
          prerelease: false
          make_latest: true

      - name: Bump version to next patch and add -SNAPSHOT suffix
        run: ./gradlew bumpVersion

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          message: 'Re-add -SNAPSHOT suffix'

